# Generated by Django 5.2.3 on 2025-07-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('details', models.TextField(default='This is cool!')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10000)),
                ('summery', models.TextField(blank=True)),
            ],
        ),
    ]
