# Generated by Django 5.2.3 on 2025-07-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.TextField(),
        ),
    ]
