# Generated by Django 5.2.3 on 2025-07-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_products_featured_alter_products_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Featured',
            field=models.BooleanField(blank=True),
        ),
    ]
