# Generated by Django 5.2.3 on 2025-07-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_products_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='summery',
            field=models.TextField(),
        ),
    ]
